version: '3.7'
networks:
  databases_dbnet:
    external: true
  laravel:
    driver: bridge
services:
  apache:
    container_name: '${PROJECT_NAME}_apache'
    build: './apache'
    restart: unless-stopped
    ports: 
      - 80:80
    volumes:
      - ./public_html:/usr/local/apache2/htdocs
    depends_on:
      - php
    networks:
      - laravel
    
  php:
    container_name: '${PROJECT_NAME}_php'
    restart: unless-stopped
    build:
      context: './php'
      args:
        - INSTALL_ELASTIC_SEARCH=${PHP_INSTALL_ELASTIC_SEARCH}
        - INSTALL_COMPOSER=${PHP_INSTALL_COMPOSER}
        - INSTALL_PDO_SQLSRV=${PHP_INSTALL_PDO_SQLSRV}
        - INSTALL_XDEBUG=${PHP_INSTALL_XDEBUG}
        - PHPUSER=${PHP_USER}
        - PHPGROUP=${PHP_GROUP:-1000}
    volumes:
      - ./public_html:/usr/local/apache2/htdocs
      - ./tmp:/usr/local/tmp
    extra_hosts:
      - "host.docker.internal:${APACHE_CONTAINER_IP}"
    networks:
      - databases_dbnet
      - laravel

  composer:
    container_name: '${PROJECT_NAME}_composer'
    build:
      context: './composer'
      args:
        - PHPUSER=${PHP_USER}
        - PHPGROUP=${PHP_GROUP:-1000}
    volumes:
      - ./public_html:/usr/local/apache2/htdocs
    depends_on:
      - php
    user: ${PHP_USER}
    entrypoint: ['composer']
    networks:
    - laravel

  laravel:
    container_name: '${PROJECT_NAME}_laravel'
    build:
      context: './composer'
      args:
        - PHPUSER=${PHP_USER}
        - PHPGROUP=${PHP_GROUP:-1000}
    volumes:
      - ./public_html:/usr/local/apache2/htdocs
    depends_on:
      - php
    user: ${PHP_USER}
    entrypoint: ['laravel']
    networks:
    - laravel

  npm:
    container_name: '${PROJECT_NAME}_npm'
    image: node:14.17
    volumes:
      - ./public_html:/usr/local/apache2/htdocs
    ports:
      - 3000:3000
      - 3001:3001
    working_dir: /usr/local/apache2/htdocs
    entrypoint: ['npm']
    networks:
      - laravel

  artisan:
    container_name: '${PROJECT_NAME}_artisan'
    build:
      context: './php'
    volumes:
      - ./public_html:/usr/local/apache2/htdocs
    working_dir: /usr/local/apache2/htdocs
    entrypoint: ['php', '/usr/local/apache2/htdocs/artisan']
    user: ${PHP_USER}
    networks:
      - databases_dbnet
      - laravel

  mailhog:
    container_name: '${PROJECT_NAME}_mailhog'
    build: './mailhog'
    ports:
      - 8025:8025
    networks:
      - laravel